name: Our CI

on:
  pull_request: {}
  push:
    branches:
      - main  
      - other-branch
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:  # Changed from 'step' to 'steps'
      - uses: actions/checkout@v4
      - name: Set up Python 3.11  # Added a name for clarity
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Changed from array to string
      - name: Install Python3 package
        run: python -m pip install .[test]
      - name: Run tests
        run: python -m pytest

  matrix-test:  # Added indentation to align with 'test'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.11"]
        include:
          - os: macos-latest
            python-version: "3.10"  # Changed key from 'python' to 'python-version'

    runs-on: ${{ matrix.os }}
    steps:  # Added 'steps' section
      - uses: actions/checkout@v4
      - name: Set up Python  # Added a name for clarity
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Fixed typo: 'matric' to 'matrix'
      - name: Install Python package
        run: python3 -m pip install .[test]
      - name: Run tests
        run: python -m pytest
      - name: Example step that runs on Linux
        if: runner.os == 'Linux'  # Changed double quotes to single quotes
        run: echo "This is linux"
      - name: This step generates output
        id: step-with-output
        run: echo "some-variable=something" >> $GITHUB_ENV  # Changed from GITHUB_OUTPUT to GITHUB_ENV
      - run: echo "${{ steps.step-with-output.outputs.some-variable }}"  # Fixed typo in expression syntax
